"""Add code type to Product table

Revision ID: dcb01f39dce5
Revises: 1938ff520df5
Create Date: 2021-06-21 21:46:13.570512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb01f39dce5'
down_revision = '1938ff520df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('code_type', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'code_type')
    # ### end Alembic commands ###
